apiVersion: v1
kind: Service
metadata:
  name: backend
spec: 
  type: ClusterIP
  selector: 
    app: backend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-dep
  labels: 
    app: backend
spec: 
  replicas: 2
  selector:
    matchLabels:  
      app: backend 
  strategy: 
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata: 
      labels:
        app: backend
    spec: 
      containers:
      - name: backend
        image: reeceqa/python-backend
        ports:
        - containerPort: 5001