apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec: 
  type: LoadBalancer
  selector: 
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-dep
  labels: 
    app: frontend
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: frontend 
  strategy: 
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata: 
      labels:
        app: frontend
    spec: 
      containers:
      - name: frontend-app
        image: reeceqa/python-frontend
        ports:
        - containerPort: 5000