version: "3.8"
services:
  db:
    build: ./db
    image: database-layer:latest
    container_name: flask-db
    ports:
    - target: 3306
      published: 3306
  flask-app:
    container_name: flask-app
    build: ./flask-app
    image: flask-app:latest
    ports: 
    - "5000:5000"
  nginx:
    container_name: nginx
    image: nginx
    ports: 
    - "80:80"
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf